workflows:
  build-android-ios:
    name: Build Android and iOS (Release)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      # Build Android APK (release)
      - flutter build apk --release
    artifacts:
      # Android artifact
      - build/app/outputs/flutter-apk/app-release.apk
