workflows:
  build-android-ios:
    name: Build Android and iOS (Release)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      # Build Android APK (release)
      - flutter build apk --release
      
      # Build iOS IPA (release)
      # (sẽ cần chứng chỉ & provisioning profile hợp lệ)
      - flutter build ipa --release --no-codesign
    artifacts:
      # Android artifact
      - build/app/outputs/flutter-apk/app-release.apk

      # iOS artifact (IPA)
      - build/ios/ipa/*.ipa
